---
title:  "Practicing Software Engineer"
date:  2018-05-01
---

title: Practicing Software Engineer
author: Mano Beeslaar
email: mano.beeslaar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  coding, software engineer, getting things done

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
